### ISSUE TITLE
MethodNotFoundException occurred while store token with redis

### ISSUE THREAD

**Issue by rieonke** [spring-projects/spring-security-oauth#1230]
the exception was
```
Handling error: NestedServletException, Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V
```

Env:
- Spring Boot M6
- Spring Data Redis 2.0.1.RELEASE
- Spring Cloud Finchley.M4

Code throws which throws exception blow:
line 157 `conn.set(accessKey, serializedAccessToken); `

https://github.com/spring-projects/spring-security-oauth/blob/0c034e4dfac53c6f736a3d7e858bae37328e0fab/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/store/redis/RedisTokenStore.java#L154-L163

**Comment by rieonke** [comment]
update:
the `set(String,String)` method was deprecated in `spring-data-redis`  at version `2.0`,
use `RedisStringCommands#set` instead,
so it should be 
```
conn.stringCommands().set(...)
```

**Comment by rieonke** [comment]
update
it works fine after upgrading the `spring-date-redis`  dependency version to `2.0.1.RELEASE` 
and `jedis` to `2.9.0` BTW

**Comment by jgrandja** [comment]
@rieonke Thanks for updating with the solution on explicitly declaring the dependencies. I'm going to close this issue.

**Comment by hardikbeladiya** [comment]
@jgrandja . This issue still happening in         
<dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>        
<dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
            <version>2.0.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>

Error : java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V

**Comment by macdao** [comment]
same issue as @hardikbeladiya 

I believe it's because the RedisTokenStore compiled against RedisConnection with an old version ( actually spring-data-redis 1.5.0.RELEASE https://github.com/spring-projects/spring-security-oauth/blob/2.2.1.RELEASE/spring-security-oauth2/pom.xml)
A re-compile against the correct spring-data-redis will fix the issue

@rieonke a deprecated won't cause NoSuchMethodError

**Comment by RogierdeRuijter** [comment]
@jgrandja. Same problem: 

org.springframework.security.oauth.boot
spring-security-oauth2-autoconfigure:
2.0.0.BUILD-SNAPSHOT'

org.springframework.data
spring-data-redis
2.0.1.RELEASE'

redis.clients
jedis
2.9.0

java.lang.NoSuchMethodError:org.springframework.data.redis.connection.RedisConnection.set([B[B)V

**Comment by macdao** [comment]
append more information.

The signature of method `org.springframework.data.redis.connection.RedisConnection.set` changed from `void set(byte[] key, byte[] value)` (in spring-data-redis [1.5.0.RELEASE](https://github.com/spring-projects/spring-data-redis/blob/v1.5.0.RELEASE/src/main/java/org/springframework/data/redis/connection/RedisStringCommands.java)) to `Boolean set(byte[] key, byte[] value)` (since [2.0.0.RELEASE](https://github.com/spring-projects/spring-data-redis/blob/2.0.0.RELEASE/src/main/java/org/springframework/data/redis/connection/RedisStringCommands.java)), so the NoSuchMethodError thrown.

**Comment by sebarswee** [comment]
This issue happening in

spring-security-oauth2-autoconfigure:2.0.0.RELEASE

spring-data-redis:2.0.5.RELEASE

redis.clients:jedis:2.9.0

**Comment by jayzch** [comment]
spring-security-oauth2-autoconfigure:2.0.0.RELEASE

spring-data-redis:2.0.5.RELEASE

redis.clients:jedis:2.9.0

the same problem happened.

re-compile spring-security-oauth2 by upgrading the spring-date-redis dependency version to 2.0.5.RELEASE

**Comment by wilkinsona** [comment]
I think this issue needs to be re-opened. As things stand org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.0.0.RELEASE does not work with Spring Boot 2.0 when using Redis to store tokens.

As has already been noted above, the underlying problem is that `org.springframework.security.oauth:spring-security-oauth2` compiles against Spring Data Redis 1.5 whereas Boot 2.0 uses Spring Data Redis 2.0.x. The latter is not binary compatible with the former so a failure occurs at runtime:

```
Caused by: java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V
	at org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStore.storeAccessToken(RedisTokenStore.java:160) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:122) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:561) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 76 common frames omitted
```

**Comment by jgrandja** [comment]
A fix is in process #1319

**Comment by fcjxxl** [comment]
same error still exists, My pom.xml below:
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
	</parent>

	
	<dependency>
		<groupId>org.springframework.security.oauth.boot</groupId>
		<artifactId>spring-security-oauth2-autoconfigure</artifactId>
		<version>2.0.0.RELEASE</version>
	</dependency>
	
	
	<dependency>
		<groupId>org.springframework.security.oauth</groupId>
		<artifactId>spring-security-oauth</artifactId>
		<version>2.3.2.RELEASE</version>
	</dependency>

**Comment by jgrandja** [comment]
@fcjxxl Other users have reported that it has been fixed. See #1319.
I noticed your POM uses `spring-security-oauth`...it should be `spring-security-oauth2`

**Comment by yy306525121** [comment]
im use spring-cloud-starter-oauth2 and i have this problem too,  
![image](https://user-images.githubusercontent.com/12985872/42669326-54291bb0-8687-11e8-9c3d-b5fc77727552.png)
i found 
![image](https://user-images.githubusercontent.com/12985872/42669336-6d09887c-8687-11e8-8e59-7a6244e89672.png)
spring-security-oauth2 is 2.2.1.RELEASE, bug in 2.2.1.RELEASE the RedisTokenStore.java is 
![image](https://user-images.githubusercontent.com/12985872/42669373-9ba0b30e-8687-11e8-9208-7a8d64708977.png)
but after 2.3.1RELEASE is
![image](https://user-images.githubusercontent.com/12985872/42669460-2a7b587c-8688-11e8-8737-888be647d768.png)
so i do like this 
![image](https://user-images.githubusercontent.com/12985872/42669492-5ec89dd8-8688-11e8-9b34-4eb6965e7204.png)

**Comment by HarishKumarGudivada** [comment]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.8.RELEASE</version>
		<relativePath/> 
	</parent>


<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>1.5.10.RELEASE</version>
		</dependency>



<dependency>
			<groupId>org.springframework.security.oauth.boot</groupId>
			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
			<version>2.0.0.RELEASE</version>
		</dependency>



getting following error : java.lang.NoSuchMethodError: org.springframework.util.Assert.state(ZLjava/util/function/Supplier;)V


if i commented spring-security-oauth2-autoconfigure , its working fine. I am trying to use this dependency in existing project. Please , help in solving the above issue

**Comment by rwinch** [comment]
@HarishKumarGudivada You are bringing in spring-security-oauth2-autoconfigure on a Boot 1.x project which will not work. For Boot 1.x the autoconfigure support is included in the Boot autoconfig.

PS: In the future please create questions on StackOverflow and not on GitHub (especially not on a closed issue which may not be noticed)

**Comment by FaanJoeng** [comment]
That's my solution:
![solution](https://user-images.githubusercontent.com/14855496/45946110-70482f00-c022-11e8-8c0b-9704d8419b66.jpg)

**Comment by ddkcstream** [comment]
> That's my solution:
> ![solution](https://user-images.githubusercontent.com/14855496/45946110-70482f00-c022-11e8-8c0b-9704d8419b66.jpg)

got this solution

**Comment by abccbaandy** [comment]
> That's my solution:
> ![solution](https://user-images.githubusercontent.com/14855496/45946110-70482f00-c022-11e8-8c0b-9704d8419b66.jpg)

You don't need exclude `spring-security-oauth2` actually. 2nd dependency will override the version.
